import streamlit as st
import re
import json
from pptx import Presentation
from pptx.util import Inches
import io

st.set_page_config(page_title="TinySlide AI", layout="wide")

st.title("TinySlide AI")
st.subheader("Offline Text-to-Slide Generator")

text = st.text_area("Paste your notes here:", height=250)

def clean_sentences(text):
    sentences = re.split(r'(?<=[.!?]) +', text.strip())
    return [s.strip() for s in sentences if len(s.strip()) > 10]

def generate_title(text):
    words = text.split()
    return " ".join(words[:6]).title() if words else "Untitled Presentation"
def generate_slide_heading(chunk):
    text = " ".join(chunk).lower()

    if "benefit" in text or "advantage" in text:
        return "Key Benefits"

    if "problem" in text or "challenge" in text:
        return "Problem Statement"

    if "solution" in text or "solve" in text:
        return "Proposed Solution"

    if "example" in text:
        return "Example"

    if "process" in text or "step" in text:
        return "Process Overview"

    words = chunk[0].split()
    return " ".join(words[:6]).title()
def make_slides(text):
    sentences = clean_sentences(text)
    title = generate_title(text)

    slides = []
    chunk_size = 3

    for i in range(0, len(sentences), chunk_size):
        chunk = sentences[i:i+chunk_size]

        slide = {
            "heading": generate_slide_heading(chunk),
            "bullets": [clean_bullet(s) for s in chunk],
            "layout": suggest_layout(chunk)
        }

        slides.append(slide)

    return {
        "title": title,
        "slides": slides
    }
def clean_bullet(sentence):
    sentence = sentence.strip()

    remove_words = ["basically", "actually", "very", "really"]
    for word in remove_words:
        sentence = sentence.replace(word, "")

    sentence = sentence.strip()

    if len(sentence) > 120:
        sentence = sentence[:117] + "..."

    return sentence[0].upper() + sentence[1:] if sentence else sentence
def suggest_layout(chunk):
    bullet_count = len(chunk)

    if bullet_count <= 2:
        return "title_and_content"

    elif bullet_count <= 4:
        return "two_column"

    else:
        return "comparison"
def create_pptx(result):
    prs = Presentation()

    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = result["title"]
    title_slide.placeholders[1].text = "Generated by TinySlide AI"

    for slide_data in result["slides"]:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = slide_data["heading"]

        content = slide.placeholders[1]
        content.text = ""

        for bullet in slide_data["bullets"]:
            p = content.text_frame.add_paragraph()
            p.text = bullet
            p.level = 0

    pptx_file = io.BytesIO()
    prs.save(pptx_file)
    pptx_file.seek(0)

    return pptx_file

if st.button("Generate Slides"):
    if text.strip():
        result = make_slides(text)
        json_data = json.dumps(result, indent=4)

        pptx_file = create_pptx(result)

        st.download_button(
            label="Download PowerPoint",
            data=pptx_file,
            file_name="generated_slides.pptx",
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
        )

        st.download_button(
            label="Download JSON",
            data=json_data,
            file_name="generated_slides.json",
            mime="application/json"
        )

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Generated JSON")
            st.json(result)

        with col2:
            st.subheader("Slide Preview")
            st.markdown(f"# {result['title']}")

            for slide in result["slides"]:
                st.markdown("---")
                st.markdown(f"## {slide['heading']}")
                for bullet in slide["bullets"]:
                    st.markdown(f"- {bullet}")

    else:
        st.warning("Please enter some text.")
        